name: dio_http_client_example
description: Demonstrates how to use the dio_http_client plugin.

publish_to: 'none' 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.1
  dio_http_client:
    path: ../

  cupertino_icons: ^1.0.2
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true