name: dio_http_client
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.matteoantolini.dio_http_client
        pluginClass: DioHttpClientPlugin
      ios:
        pluginClass: DioHttpClientPlugin
      linux:
        pluginClass: DioHttpClientPlugin
      macos:
        pluginClass: DioHttpClientPlugin
      windows:
        pluginClass: DioHttpClientPluginCApi
      web:
        pluginClass: DioHttpClientWeb
        fileName: dio_http_client_web.dart